[package]
name = "launch-rdp"
version = "0.1.0"
authors = ["kykc"]

[dependencies]
clap = "^2.32"
dirs = "^1.0"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
gtk = {version = "^0.5", features = ["v3_20"]}
gio = "^0.5"
rpassword = "^2.1"